apiVersion: v1
kind: Namespace
metadata:
  name: playns
---
apiVersion: v1
kind: Pod
metadata:
  namespace: playns
  name: playpod
  labels:
    app: newapps
    env: dev
    client: abc
spec:
  containers:
    - name: ubuntu
      image: ubuntu:trusty
      command: [/bin/sh, -c, "sleep 3600"]
