apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  serviceAccountName: myserviceaccount
  containers:
    - name: myapp
      image: nginx
